name = input("Enter your Name:")
address1 = input('Enter address line1:')
address2 = input('Enter address line2:')
address3 = input('Enter address line3:')
city = input('Enter city Name:')
state = input('Enter state Name:')
pin = input('Enter pin:')
print(name)
print('Adress:')
print(address1, ',')
print(address2, ',')
print(address3, ',')
print(city, '-', pin)
print(state)